cashubtc/cashu.me

- src/components/SettingsView.vue
- src/pages/WalletPage.vue
fix todos in #6: addMint in SettingsView and splitToSend in melt
> fix todos in #6: addMint in SettingsView and splitToSend in melt

- package.json
Fix some basic package.json stuff. Vue 3 has this minimum node version
> fix(build): Add missing dependency, fix minimum node, add quasar scripts

- src/pages/WalletPage.vue
> fix race condition

- src/components/WelcomeDialog.vue
- src/pages/WalletPage.vue
- src/stores/mints.js
Minimum restore backup functionality. It works.
> Restore local storage state from backup file

- .vscode/extensions.json
- .vscode/settings.json
This will help clean up the Explorer panel.
Hidden files can be shown easily by ticking checkboxes on the `Explorer > Hidden Items ` accordion drawer on VSCode.
> Recommend explorer-exclude & exclude hidden files

- src/pages/WalletPage.vue
Update NUT-04 https://github.com/cashubtc/nuts/pull/14
> nut4 update: payment_hash to hash

- src/stores/mints.ts
Warn user via `!confirm` in `mints.ts`. But I think it would be prettier using one of the dialog boxes, which would need a little more work.
Mentioned in #27.
All tests passing.
> Delete mint warning

- package-lock.json
- src/components/SettingsView.vue
- src/stores/mints.ts
> Warn user before deleting a mint with dialogue box.

- src/stores/mints.ts
Remove the second browser dialog after the better one was merged in #57
> Remove mint: No second dialog when removing a mint

- src/pages/WalletPage.vue
Too buggy, I'm afraid of the `Could not verify proofs' bug.
> remove pending checks on startup

- Dockerfile
- README.md
- docker-compose.yaml
Added Dockerfile and compose file to quickly build & run the app. Only prerequisite is to have docker installed.
> containerize the app

- package-lock.json
- package.json
- src/components/SettingsView.vue
- src/stores/ndk.ts
This PR adds a new setting for discovering mints via [NIP-87](https://github.com/nostr-protocol/nips/blob/c6bfb1888b7e8971a246a6ba5fa8ecead963de6d/87.md)
> Add nostr mint discovery using ndk

- src/components/InvoiceDetailDialog.vue
- src/components/MainHeader.vue
- src/components/PayInvoiceDialog.vue
- src/components/ReceiveTokenDialog.vue
- src/components/SendTokenDialog.vue
- src/stores/wallet.ts
Wallet shows if the amount can be sent while remaining offline, and if possible, does so.
> Send Ecash offline and show user if possible

- src/components/HistoryTable.vue
- src/components/InvoicesTable.vue
- src/components/ReceiveTokenDialog.vue
- src/components/SendTokenDialog.vue
- src/stores/tokens.ts
- src/stores/wallet.ts
Allows sending user to delete the ecash from the history
and the receiving user to store the ecash in the history to receive it later
> Delete ecash history and receive later

- src/components/SettingsView.vue
Found a small typo in the SettingsView.vue
> Fixed typo in SettingsView.vue

- src/components/PayInvoiceDialog.vue
This pull request refactors the rendering of the `payInvoiceData` in the code. It introduces a new component `ToggleUnit.vue` and updates the rendering logic for the `payInvoiceData.meltQuote` response and error messages. Additionally, it adds watchers for the `activeMintUrl` and `activeUnit` properties to trigger the `meltQuote` function.
> Refactor payInvoiceData rendering

- src/components/NWCDialog.vue
> NWC QR clickable

- src/components/SendTokenDialog.vue
> warning for delete token, closes #141

- src/stores/wallet.ts
add comments and remove temporary code (output selection)
> Refactor wallet proof selection logic

- src/stores/nwc.ts
This pull request fixes the NWC transaction history by creating an array of transactions from the invoice history. Each transaction includes the type (incoming or outgoing), invoice details, description, amount, and created/settled timestamps. This ensures accurate and organized transaction data.
> Fix NWC transaction history

- src/components/HistoryTable.vue
- src/components/InvoiceDetailDialog.vue
- src/components/InvoicesTable.vue
- src/components/MintSettings.vue
- src/components/PayInvoiceDialog.vue
- src/components/QrcodeReader.vue
- src/components/ReceiveTokenDialog.vue
- src/components/SendTokenDialog.vue
- src/pages/WalletPage.vue
- src/stores/mints.ts
- src/stores/tokens.ts
- src/stores/wallet.ts
This pull request includes several commits that address various issues related to invoices and mints. The changes include fixing counter increment, decoding tokens correctly, re-adding pending tokens to history, and correctly checking pending outgoing invoices. Additionally, the pull request fixes issues with activating mint URLs and forces the activation of the mint URL when pressed. The changes also include UI improvements such as updating the text and icons for sending and receiving invoices.
> "Fix various issues with invoices and mints"

- src/components/iOSPWAPrompt.vue
check for safari user agent but it doesnt work / matter because in ios all browsers have the safari user agend (even chrome) reeeeee
> Fix iOS Safari user agent check

- src/boot/base.js
- src/components/BalanceView.vue
- src/components/InvoiceDetailDialog.vue
- src/components/PayInvoiceDialog.vue
- src/stores/mints.ts
- src/stores/ui.ts
- src/stores/wallet.ts
https://github.com/cashubtc/cashu.me/issues/183
> Added ability to hide amounts in the UI with ****

- package-lock.json
- src/stores/wallet.ts
for https://github.com/cashubtc/cashu.me/issues/189
> Remove unneeded reserved field in token to send

- src/components/MintSettings.vue
- src/components/NoMintWarnBanner.vue
- src/components/SettingsView.vue
- src/js/eventBus.js
This pull request adds an event bus and implements scrolling to the mint element when the "Add mint" button is clicked. The event bus allows for communication between components, and the scroll functionality enhances the user experience by automatically scrolling to the mint element when it is added.
> Implement event bus and scroll to mint element

- src/stores/mints.ts
This pull request restores all keys from a backup. Instead of setting each key individually, the code now uses a loop to set each key from the backup object. This improves code readability and reduces redundancy.
> Restore all keys

- src/components/PayInvoiceDialog.vue
- src/stores/wallet.ts
This pull request fixes an issue with the lnurl qr decode functionality. The code changes ensure that the lnurlpay domain is correctly retrieved and used in the payment process. Additionally, the code now handles cases where the lnurlpay amount is null, displaying an error message.
> Fix lnurl qr decode

- src/stores/wallet.ts
this PR cleans up cashu token parsing
> cleanup url token parsing

- src/components/SendTokenDialog.vue
> fix v3 toggle

- src/css/app.scss
Update the checkbox SVG color to use the dark theme variable for better visibility.
> Fix checkbox color

- src/components/ReceiveTokenDialog.vue
Improve the handling of tokens in the receive ecash dialog by updating the logic for adding pending tokens to history. This change ensures that the correct token information is processed and displayed.
> Fix "Later" button functionality in receive ecash dialog

- src/components/ReceiveTokenDialog.vue
Make small edits to button classes and update notification messages for consistency.
> Minor UI and notification text adjustments

- src/components/ReceiveTokenDialog.vue
- src/components/SendTokenDialog.vue
> Thelmuxkriovar/emoji copy: Token encoded in Emoji 

- src/components/MintDetailsDialog.vue
- src/components/MintMotdMessage.vue
Updated action buttons sections on mint info screen.
> Update Mint Info Action Buttons

- src/components/ReceiveTokenDialog.vue
To resolve https://github.com/cashubtc/cashu.me/issues/342
The decodePeanut function now checks ALL input for hidden data, making it more copy/paste resilient.
It also allows decoding of non-peanut emojis.
> Make peanut checking more robust

- src/components/SendTokenDialog.vue
- src/stores/payment-request.ts
Improvements include adding language support for NFC records, enhancing user notifications during NFC operations, and implementing unit activation in payment requests with appropriate warnings for unsupported units.
> Select payment request and NFC fixes

- src/components/InvoicesTable.vue
- src/stores/wallet.ts
Enhance invoice handling by automatically checking and displaying errors related to melting invoices. Adjustments ensure that the system responds appropriately based on the invoice amount and status.
> Show error and melt automatically

- src/stores/p2pk.ts
This PR improves P2PK pubkey handling in accordance with [NUT-11](https://github.com/cashubtc/nuts/blob/main/11.md).
It aims to find a pubkey that can witness the token.
The logic is as follows:
- If `locktime` is active or not set:
- check the additional `pubkeys` tag for a match to user's stored pubkeys, return first found if `n_sigs` is >=1
- fall back to the main `data` pubkey, so user can see the token is locked
- (NOTE: `data` pubkey may or may not be a match to user's stored pubkeys)
- If `locktime` has expired:
- check the `refund` tag for a match to user's stored pubkeys, return first found
- fall back to the first `refund` tag pubkey, so user can see the token is still locked
- (NOTE: first `refund` tag pubkey may or may not be a match to user's stored pubkeys)
-  If no refund …
> Try harder to find an actionable P2PK Pubkey

- .github/workflows/test.yml
- Runs tests on push to main/develop branches and PRs
- Tests on Node.js 18.x and 20.x
- Includes linting and formatting checks
- Uses npm ci for faster, reliable dependency installation
> Add GitHub workflow to run Vitest tests

- src/components/PayInvoiceDialog.vue
A tentative attempt to solve #411 
Let me know how I did.
> Fix: Multinut payment availability

- src/components/HistoryTable.vue
@callebtc this fixes the issues on mobile.
> fix long press reclaim not working on mobile
