cashubtc/cashu.me

- src/components/NoMintWarnBanner.vue
> Fix Typo in NoMintWarnBanner

- package.json
- src/js/token.js
- src/pages/WalletPage.vue
This moves the token code from the Vue component into a standalone file.
This also adds some types via [JSDoc](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html) to provide some clarity about what these functions should expect.
Would be great to add unit testing around this at some point too, extracting these more "pure business logic" functions away from the Vue code, and testing them in isolation.
> chore(js): move token code to file

- src/components/WelcomeDialog.vue
- src/stores/mints.js
Some UI fixes upon #21 
Todo: move `restoreFromBackup` from `mint.js` to a new pinia store in `wallet.js`.
> Restore wallet backup

- src/pages/WalletPage.vue
Removed legacy V2 Token switch and functions in `WalletPage.vue`.
Mentioned in #29. 
All tests passing.
> Remove legacy V2 Token switch and functions

- src/boot/base.js
- src/components/BalanceView.vue
- src/pages/WalletPage.vue
PR #50 republished on origin/
Updates, as indicated in https://github.com/cashubtc/cashu.me/issues/45 and mentioned in https://github.com/cashubtc/cashu.me/issues/42 which include:
- increase size of refresh button in balance view and add mouse over
- add mint mouse over in balance view
- give feedback if pending tokens are refreshed with new notification: `notifyRefreshed`
- increase `last_n` in `checkPendingTokens`, because it was not checking all tokens if number of token in history was to high
- linting 
All tests are passing.
￼
> [UI] improve wallet refresh

- src/components/HistoryTable.vue
republished #53 
I wanted to have a better fingerprint of the Tokens in the overview for nuts control. So in this PR I would suggest slicing 10 letters by using indexes of half of the token length + 10. Additionally, using the padding of 8 letters in front and at the end.
> [UI] slice 10 letters from center of token for better fingerprint

- src/components/QrcodeReader.vue
Some animated QR codes capitalize the `ur:` prefix, making it necessary to check for all variants.
> Make QR prefix check case-insensitive

- src/components/WelcomeDialog.vue
Should fix the below:
and clarify that the code is open source.
> Fix WelcomeDialog typo, add license clarity

- src/stores/wallet.ts
This pull request fixes the melt quote error that occurs when processing an invoice. The error message is now cleared before attempting to process the invoice.
> Fix melt quote error

- package-lock.json
- src/css/base.scss
This pull request disables the webkit scrollbar by adding the CSS rule `::-webkit-scrollbar { display: none; }`. This improves the visual appearance of the application by removing the scrollbar.
> Disable webkit scrollbar

- src/stores/nwc.ts
This pull request adds functionality to notify warnings for NWC errors. It includes changes to the `useNWCStore` module to display warning messages using the `notifyWarning` function from the `src/js/notify` module. This will improve the user experience by providing more informative error messages when encountering issues related to melt quotes, active units, and quota limits.
> Notify warnings for NWC errors

- src/css/base.scss
In the cyber theme, the info background color is the same as the button font color, so the button that toggles between currencies is not visible.  
Before: 
After:
> Fix for invisible button in the cyber theme

- src/stores/wallet.ts
This pull request fixes an issue with the coin selection logic in the code. Previously, the logic was not correctly selecting the next bigger proof as a fallback. This PR updates the logic to ensure that the next bigger proof is correctly selected.
> Fix coin select gte

- src/stores/nwc.ts
- src/stores/wallet.ts
This pull request updates the nwc amount calculation in the useNWCStore function to convert the amount to milli-satoshis. Additionally, it updates the memo field for outgoing invoices in the useWalletStore function to "Outgoing invoice".
> Update nwc amount to milli-satoshis

- src/components/NWCDialog.vue
The NWC dialog has been updated with a new design and a more prominent warning message. The warning now clearly states that anyone with access to the connection string can initiate payments from the wallet, emphasizing the importance of not sharing it.
> Update NWC dialog design and warning message

- src/components/WelcomeDialog.vue
- src/components/iOSPWAPrompt.vue
- src/pages/WalletPage.vue
This pull request adds a new component called iOSPWAPrompt.vue, which displays a prompt for iOS users to add the app to their home screen. The component is conditionally rendered based on the user's device and whether they have already seen the prompt. The prompt includes instructions and a close button. Additionally, the iOSPWAPrompt component is imported and used in the main App.vue file.
> Add iOS PWA prompt

- src/components/PayInvoiceDialog.vue
- src/components/SendTokenDialog.vue
- src/stores/wallet.ts
This pull request updates the send dialog to respect the `activeMintBalance` instead of `activeBalance` when determining if the mint balance is too low. It also modifies the buttons in the send dialog to disable the "Send" button and display a message when the mint balance is too low.
> Respect activeMintBalance instead of activeBalance and modify buttons in send dialog

- src/components/SettingsView.vue
- src/css/base.scss
This pull request adds a link to a recovery tool in the wallet's user interface. Previously, the wallet did not support seed phrase recovery, but now users can use the provided tool or a different Cashu wallet to recover their wallet using the seed phrase. The link is displayed in the user interface and is styled to be easily recognizable.
> Add link to recovery tool

- .vscode/settings.json
- src/components/HistoryTable.vue
- src/components/InvoiceDetailDialog.vue
- src/components/InvoicesTable.vue
- src/components/MintSettings.vue
- src/components/ReceiveTokenDialog.vue
- src/components/SendTokenDialog.vue
- src/components/SettingsView.vue
- src/pages/WalletPage.vue
- src/stores/nostr.ts
- src/stores/npubcash.ts
- src/stores/nwc.ts
> Lightning address + diverse nostr signers

- src/boot/base.js
- src/components/InvoiceDetailDialog.vue
- src/components/MintDetailsDialog.vue
- src/components/SendTokenDialog.vue
- src/components/ToggleUnit.vue
- src/stores/mints.ts
- src/stores/ui.ts
The computation of the `activeUnitLabel` in the `useMintsStore` has been fixed to correctly return the label for the active unit. Additionally, support for the EUR and mSAT units has been added. This allows the user to toggle between BTC, USD, EUR, and mSAT units in the application.
> Fix activeUnitLabel computation and add support for EUR and mSAT units

- src/components/SettingsView.vue
- src/stores/nostr.ts
- src/stores/npubcash.ts
This pull request updates the Nostr Wallet Connect functionality by making the method of using private keys more secure. Instead of entering the private key directly, users are now advised against it due to security risks. Additionally, the pull request includes a fix to ensure that the signer is initialized if it is not already set. This ensures a smoother user experience when generating Nip98 events.
> Update Nostr Wallet Connect functionality

- src/components/BalanceView.vue
- src/stores/wallet.ts
* Added fetchBitcoinPriceUSD to wallet.ts, which fetches the price from Coinbase
* Modified `lnurlPayFirst`: avoid potentially repeated query.
* Modified `lnurlPaySecond`: if `mintStore.activeUnit` is `usd` then calculate the equivalent in satoshis and use that for the invoice.
> [FIX] Convert USD amount to SATs before requesting a lnurl invoice

- src/components/BalanceView.vue
- src/components/P2PKDialog.vue
- src/components/ReceiveTokenDialog.vue
- src/components/ToggleUnit.vue
- src/stores/p2pk.ts
- src/stores/wallet.ts
This pull request includes several fixes related to P2PK key generation and display. The changes include:
- Fixing the generation of P2PK keys in the receive screen
- Fixing the units displayed in the ToggleUnit component
- Handling P2PK keys in the handleP2PK function of the WalletStore
- Updating the P2PK component to display the correct P2PK key information
- Adding a button to generate new P2PK keys in the P2PK component
These changes address issues with P2PK key generation and display in the application.
> Fix P2PK key generation and display

- src/components/SettingsView.vue
This pull request includes changes to sort counters by URL. The code changes ensure that the counters are displayed in the correct order based on the URL.
> Sort counters by URL

- src/components/SendDialog.vue
- src/pages/WalletPage.vue
- src/stores/sendTokensStore.ts
This pull request fixes an issue where the `amount` field was being assigned an empty string instead of `null`. The `amount` field is now correctly assigned `null` in the `sendData` object. This ensures that the `amount` field is properly initialized and avoids any potential issues related to incorrect data types.
> Fix null assignment for amount field

- src/stores/nwc.ts
Hi, a stacker reported that NWC of cashu.me fails to link with Stacker News, see https://stacker.news/items/645420:
> I'm getting and error trying to connect Cashu.me to Stacker.News using NWC in the wallets sections. The error I'm getting is EOSE received without info event. Does anyone see this? Cashu.me NWC works for other websites like NoStudel and Habla.
>
> The rest of my logs look like this:
>
>> 2m	[nwc]	error	failed to attach: EOSE received without info event
>> 2m	[nwc]	info	closed connection to wss://relay.primal.net
2m	[nwc]	error	EOSE received without info event
2m	[nwc]	ok	connected to wss://relay.primal.net
2m	[nwc]	info	requesting info event from wss://relay.primal.net
3m	[nwc]	error	failed to attach: EOSE received without info event
3m	[nwc]	info	closed connection to …
> Fix check if info event was already published

- src/components/PayInvoiceDialog.vue
- src/components/ReceiveTokenDialog.vue
- src/components/TokenInformation.vue
- src/js/wallet-helpers.js
This pull request includes changes to shorten the display of the mint URL. The `getShortUrl` function has been updated to cut the URL if it is too long, keeping the first half and the last half of the URL. Additionally, the `q-chip` component has been modified to display the shortened URL.
> Shorten mint URL

- src/stores/nostr.ts
This pull request updates the `useNostrStore` to compute the `seedSignerPrivateKeyNsec` dynamically instead of storing it in local storage. The `seedSignerPrivateKeyNsec` is now calculated using the `seedSignerPrivateKey` value and the `nip19.nsecEncode` function. This change ensures that the `seedSignerPrivateKeyNsec` is always up-to-date and eliminates the need to store it separately.
> Compute nsec dynamically

- package-lock.json
- package.json
- src/stores/wallet.ts
Correct the return type of the mintProofs function and update the cashu-ts dependency to version 2.0.0-rc3, which includes various improvements and fixes.
> Fix mintProofs return type and update cashu-ts to 2.0 rc3

- package-lock.json
- package.json
While rebasing #247 on main (507a9d2), I noticed that `npm install && npm run dev` no longer worked because the `@cashu/crypto` dependency was missing in package.json.
Fixed this by running `npm install @cashu/crypto`.
> Fix missing @cashu/crypto dependency

- src/components/NumericKeyboard.vue
before:
-----
after:
-----
iOS numerical keyboard for reference:
> swap comma and backspace in numeric keyboard

- src/components/BalanceView.vue
previously a click on mint url has hidden all tabs
it seems the intention was to switch to the mints tab
this fxes the fallout of #116 which internally renamed the mints tab from `settings` to `mints`
> fix click on mint url

- src/stores/nwc.ts
- src/stores/wallet.ts
This implements `make_invoice` for NWC. This has been tested as can be seen in the video (but not any further):
https://github.com/user-attachments/assets/35b5344f-92f0-42e4-a1d0-c9ebb5c307d2
I might also add `lookup_invoice` to close #196
update: added `lookup_invoice` in 34db335 but there seems to be something wrong with how invoices are confirmed, see video:
https://github.com/user-attachments/assets/060d1c71-56ab-4fbd-ba43-6f31b0a3298f
As you can see at the end, I create a mint invoice and pay it but if you close the modal before you pay, the invoice doesn't seem to get properly confirmed.
I think this is unrelated to my code.
I have noticed that if I refresh the settings page, it does not subscribe to NWC events. However, it does if I refresh on the index page.
> NWC make_invoice & lookup_invoice

- src/components/BalanceView.vue
Eliminate the tooltip that provided configuration information for mints to streamline the user interface.
> Remove tooltip from mint label

- src/css/app.scss
Closes https://github.com/cashubtc/cashu.me/issues/236
With this change pull-to-refresh will be prevented in both Chrome-based browsers and Safari.
Solution based on [stackoverflow.com/a/78711166](https://stackoverflow.com/a/78711166), [matuzo.at/blog/2022/100daysof-day53](https://www.matuzo.at/blog/2022/100daysof-day53)
I've tested on my iPhone in Safari + PWA install and Android via Android Studio.
> Prevent pull-to-refresh in Safari

- src/components/SendTokenDialog.vue
- src/stores/p2pk.ts
Allows user to enter an npub for P2PK locking.
npub is converted to officially supported 66 character P2PK format automatically on send.
If key is not a valid nip19 npub, original string is used as before
> Add automatic npub conversion for P2PK

- src/components/SettingsView.vue
- src/stores/p2pk.ts
This PR completes the integration of NOSTR npub/nsec handling for P2PK.
It allows user to add their NSEC as a P2PK key, which then means they can receive tokens locked to their NPUB.
See also this related PR: https://github.com/cashubtc/cashu.me/pull/358
Which allows users to lock tokens to an NPUB when sending
> Allow import of nsec as a p2pk key

- src/components/SettingsView.vue
- src/pages/welcome/WelcomeSlide3.vue
Instead of replacing a seed word with a placeholder of the same length, it always replaces with a fixed length placeholder (i.e. 6 chars).
Before
After
> chore: fixed length seed word placeholder

- src/stores/mints.ts
This fixes an issue with the way we convert base64 values to hex. atob returns a byte string, not an utf-8 string.
> fix: base64 to hex conversion

- src/components/BalanceView.vue
- src/components/PayInvoiceDialog.vue
- src/components/ReceiveTokenDialog.vue
- src/components/SendTokenDialog.vue
- src/components/SettingsView.vue
- src/i18n/ar-SA/index.ts
- src/i18n/de-DE/index.ts
- src/i18n/el-GR/index.ts
- src/i18n/en-US/index.ts
- src/i18n/es-ES/index.ts
- src/i18n/fr-FR/index.ts
- src/i18n/it-IT/index.ts
- src/i18n/ja-JP/index.ts
- src/i18n/sv-SE/index.ts
- src/i18n/th-TH/index.ts
- src/i18n/tr-TR/index.ts
- src/i18n/zh-CN/index.ts
- src/stores/price.ts
- src/stores/settings.ts
We currently use Coinbase for the exchange rates, but only show fiat rates in USD
This PR changes this and adds support for many more currencies.
> add support for showing balance in more fiat currencies
